// Detail-page data for the projects that have a full write-up. Shared metadata
// (title, tags, links, category) lives in lib/projects/projects.ts; the prose
// bodies live in content/projects/*.md and are read on the server, so they
// never ship to the browser.

export interface ProjectDetail {
  /** hero paragraph under the title */
  intro: string;
  image: string;
  /** extra buttons beside View Code and Live Demo, for a second way in */
  links?: Array<{ label: string; href: string; icon?: "whatsapp" }>;
  /** `contain` for logos and artwork that should not be cropped */
  imageFit?: "cover" | "contain";
  /** overrides the card tags when the detail page tells a different story */
  tags?: string[];
  timeline: string;
  team: string;
  status: string;
  features: string[];
  techStack: Record<string, string[]>;
  challenges: string[];
  learnings: string[];
  /** markdown file inside content/projects */
  file: string;
}

export const projectDetails: Record<string, ProjectDetail> = {
  "1": {
    intro:
      "A full-stack cybersecurity platform that uses machine learning to detect phishing, malware, and malicious URLs in real time, combining a trained ML model, a production-grade API, a React web dashboard, and a Chrome extension.",
    image: "/img/projects/kraven/scanner.png",
    tags: [
      "Python",
      "FastAPI",
      "scikit-learn",
      "Celery",
      "RabbitMQ",
      "React",
      "Vite",
      "TailwindCSS",
      "Docker",
      "Vercel",
      "Chrome Extension",
    ],
    timeline: "3 months",
    team: "Solo project",
    status: "Completed",
    features: [
      "Real-time malicious URL detection with ML confidence scoring",
      "14-feature URL engineering pipeline (entropy, digit ratio, path depth, etc.)",
      "RandomForest classifier trained on ~500K URLs with predict_proba output",
      "Community threat reporting that overrides ML predictions",
      "Async model retraining via Celery + RabbitMQ without API downtime",
      "Model hot-reloading that swaps the updated .pkl file without a restart",
      "Chrome Extension (Manifest V3) with auto-scan and manual popup",
      "React web dashboard with detailed threat reports and one-click reporting",
      "Fully containerised backend with Docker Compose (API + worker + broker)",
    ],
    techStack: {
      "ML / Backend": [
        "Python",
        "scikit-learn",
        "FastAPI",
        "SQLAlchemy",
        "SQLite",
      ],
      "Async / Messaging": ["Celery", "RabbitMQ"],
      Frontend: [
        "React 18",
        "Vite",
        "TailwindCSS",
        "Framer Motion",
        "Flowbite",
      ],
      Extension: ["Chrome Extension (Manifest V3)", "JavaScript"],
      Deployment: ["Docker Compose", "Vercel"],
      Tools: ["Git", "Postman", "VS Code"],
    },
    challenges: [
      "Engineering meaningful features from raw URL strings without leaking label information",
      "Chrome Manifest V3 restrictions on content script redirects, which required creative workarounds",
      "Wiring async Celery retraining so it never blocks the live API",
      "Keeping the model hot-reloadable on disk without service restarts",
      "Balancing ML prediction confidence thresholds to minimise false positives",
    ],
    learnings: [
      "How to build a production Chrome Extension with Manifest V3 and its many constraints",
      "Feature engineering for URL-based ML, where entropy and structural signals are surprisingly powerful",
      "Async task queues with Celery and RabbitMQ for background model retraining",
      "Model hot-reloading patterns in production APIs",
      "How crowd-sourced intelligence can meaningfully improve ML accuracy over time",
    ],
    file: "kraven-the-hunter.md",
  },
  "2": {
    intro:
      "This is a platform that enables cleaners to find work and regular people to find cleaners, all in  real time.",
    image: "/img/projects/safi/logo.webp",
    imageFit: "contain",
    tags: [
      "AWS",
      "Docker",
      "Python",
      "Django",
      "React",
      "React Native",
      "Golang",
    ],
    timeline: "1 Year",
    team: "Mviyo Technologies",
    status: "Completed",
    features: [
      "Real Time Cleaner Discovery",
      "Rating System",
      "Secure Payments",
      "Strict KYC",
      "Smart Discovery Algorithms",
      "Job Rescheduling",
      "Dynamic Service Costing",
      "Streamlined User Interfaces",
    ],
    techStack: {
      Cloud: ["AWS", "RDS", "Redis"],
      IaC: ["Terraform", "AWS CloudFormation"],
      Monitoring: ["Portainer", "Sentry", "CloudWatch"],
      "CI/CD": ["GitHub Actions"],
      Security: ["AWS IAM", "VPC", "Security Groups"],
      Backend: ["Django", "Golang"],
      Frontend: ["React.js", "Redux"],
      Mobile: ["React Native", "Redux"],
    },
    challenges: [
      "Developing with Expo is not for the faint hearted!",
      "Adjusting the discovery Algorithm and real time client server communication",
      "Regulatory compliance with multiple regulatory bodies",
      "Background processes in mobile applications",
      "Efficient media file compression",
      "Short term data persistence",
    ],
    learnings: [
      "Well, I finally got deeper into React Native",
      "My understanding of websockets really went up a notch",
      "Deep linking in mobile apps",
      "To be honest, I already knew quite a lot here, there wasn't too much learning done",
    ],
    file: "safi-help.md",
  },
  "3": {
    intro:
      "An all in one event management platform. It Houses the ability to help event organizers post events, sell their tickets and provide means to enable users to validate those tickets.",
    image: "/img/projects/zimtickets/explore.webp",
    tags: ["Architecture", "OpenAPI", "Eraser.io"],
    timeline: "1 Year",
    team: "Mviyo Technologies",
    status: "Completed",
    features: [
      "Event Management",
      "Ticket Sales and Validation",
      "Native iOS and Android apps for discovery, checkout and ticket holding",
      "Detailed Event Analytics",
      "Secure Payment Processing",
      "Event Promotion Tools",
    ],
    techStack: {
      Frontend: ["React Native", "Next.js", "TypeScript", "Tailwind CSS"],
      Backend: ["Laravel", "PHP"],
      Database: ["MySQL"],
      Payment: ["Stripe", "Innbucks", "Ecocash", "Omari"],
      Deployment: ["Vercel", "AWS"],
      Tools: ["Smart Bear", "Eraser.io", "Postman", "Lucid Charts"],
    },
    challenges: [
      "Cost effective resource utilization.",
      "Consistent API and database design",
      "Mockable API endpoints for testing",
      "User authentication and authorization",
      "User story generation and management",
    ],
    learnings: [
      "Generating user stories and requirements from high-level descriptions",
      "Drafting API specifications and documentation",
      "Designing scalable and maintainable backend architectures",
      "Implementing best practices for API development and testing",
      "Writing Software Requirements Specifications (SRS) documents",
    ],
    file: "zimtickets.md",
  },
  "4": {
    intro:
      "An idiomatic, dependency free Go SDK for the Paynow Zimbabwe payment gateway. Web redirects, mobile express checkout on EcoCash, OneMoney and InnBucks, status polling and hash verified webhooks, behind an API that feels like the standard library.",
    image: "/img/projects/paynow/repo.webp",
    tags: [
      "Golang",
      "Payments",
      "Cryptography",
      "Ecocash",
      "Innbucks",
      "REST APIs",
      "GitHub Actions",
    ],
    timeline: "6 months, on and off",
    team: "Solo, open source",
    status: "Published, MIT licensed",
    features: [
      "Web payments returning a redirect URL for the customer and a poll URL for you",
      "Mobile express checkout charging EcoCash, OneMoney or InnBucks directly",
      "InnBucks responses carrying the authorization code, deep link and QR code",
      "Payments that behave like a cart, computing their own total as you add items",
      "Functional options for the result URL, return URL and a custom HTTP client",
      "Context on every network call, so payments can be cancelled and timed out",
      "SHA-512 request signing with automatic verification of every response hash",
      "Insertion ordered request building, because Paynow hashes fields in order",
      "Result URL webhook handling that verifies the hash before you trust the update",
      "Transaction status helpers instead of comparing raw gateway strings",
      "Sentinel errors for caller mistakes and a distinct APIError for gateway complaints",
      "A single method HTTP interface, so tests need no mocking framework or live keys",
      "Zero third party dependencies: the go.mod file is three lines long",
      "A complete runnable flow in example/main.go",
    ],
    techStack: {
      Language: ["Golang"],
      Payments: ["Paynow", "Ecocash", "OneMoney", "Innbucks"],
      Security: ["SHA-512", "Cryptography"],
      Testing: ["Go Test", "Race Detector", "Codecov"],
      CI: ["GitHub Actions", "staticcheck", "golangci-lint"],
      Distribution: ["Go Modules", "MIT License"],
    },
    challenges: [
      "Go's form encoder sorts map keys, which silently breaks a hash that depends on field order",
      "Porting from the official Node.js and Python SDKs without importing their dynamic habits into Go",
      "Deciding what belongs in an internal package so callers cannot misuse the hashing",
      "Modelling InnBucks, which answers with a code, a deep link and a QR code instead of a USSD prompt",
      "Separating caller mistakes from gateway errors so both are matchable rather than stringly typed",
      "Keeping the dependency list empty while still being pleasant to test against",
    ],
    learnings: [
      "Insertion order is part of the contract with any gateway that hashes concatenated fields",
      "Accepting a single method interface instead of *http.Client makes a library trivially mockable",
      "Functional options age far better than a config struct that keeps growing",
      "Verification you have to remember to call is verification nobody calls, so do it before handing the value back",
      "Sentinel errors plus errors.Is give callers branching they can actually rely on",
      "A CI matrix across three Go versions catches more than it costs on a library other people import",
    ],
    file: "paynow-go.md",
  },
  "5": {
    intro:
      "A general purpose AWS Lambda that sends email over SES behind an API key, written in 116 lines of Go after Mailgun's support queue ran out of patience before I did. It now carries transactional email for every other project on this page.",
    image: "/img/projects/email-lambda/repo.webp",
    tags: [
      "Golang",
      "AWS",
      "Lambda",
      "SES",
      "API Gateway",
      "IAM",
      "REST APIs",
    ],
    timeline: "One evening, then nine months of quiet running",
    team: "Solo, open source",
    status: "Published, in production",
    features: [
      "One POST with five fields sends an email through SES",
      "Static API key checked on the x-api-key header before anything else happens",
      "HTML or plain text from a single isHtml flag, so call sites need one code path",
      "Sender address supplied per request, so one function serves several verified domains",
      "SES client built once in init and reused across warm invocations",
      "Compiled bootstrap binary on the provided.al2 runtime, no interpreter to warm up",
      "Distinct 401, 400 and 500 responses so a caller can tell a bad key from a bad body",
      "Deployed as a zip, configured with one environment variable",
    ],
    techStack: {
      Language: ["Golang"],
      Compute: ["AWS Lambda", "API Gateway"],
      Email: ["AWS SES"],
      Security: ["IAM", "API Keys"],
      Distribution: ["Open Source"],
    },
    challenges: [
      "Working out that SES costs a fraction of a hosted mail API for exactly the same delivery",
      "Keeping the sender flexible without letting a caller send from a domain SES has not verified",
      "Resisting every request to add templates, attachments and retries to a function this small",
      "A header lowercase fallback that falls back to itself, still sitting in main.go nine months later",
    ],
    learnings: [
      "Building the AWS client in init rather than per request is the whole cold path optimisation",
      "A function that does one thing gets reused everywhere, and one that does six gets rewritten",
      "Vendor support quality is a technical dependency, not a procurement detail",
      "Name the repository carefully, because a typo in a URL becomes load bearing within a week",
    ],
    file: "email-lambda.md",
  },
  "6": {
    intro:
      "A multi-tenant, AI native ERP platform for Zimbabwean businesses. Point of sale, inventory, purchasing, invoicing, accounting, fixed assets, payroll and ZIMRA fiscalisation, plus mining, construction, fleet and manufacturing verticals, with every customer provisioned onto their own isolated application and database stack within minutes.",
    image: "/img/projects/vantagepoint/dashboard.webp",
    tags: [
      "Golang",
      "Fiber",
      "GORM",
      "React",
      "TypeScript",
      "Next.js",
      "PostgreSQL",
      "Redis",
      "RabbitMQ",
      "Docker Swarm",
      "OpenAI",
      "Textract",
      "React Native",
      "AWS",
      "Nginx",
    ],
    timeline: "Ongoing, over a year in",
    team: "Solo build for Dryback Technology",
    status: "Live",
    features: [
      "Eleven switchable modules per workspace, from point of sale to fund accounting for NGOs",
      "Automatic tenant provisioning: a dedicated application and Postgres stack per customer on Docker Swarm",
      "Athena, an in-process MCP style registry of read-only tools, resources and prompts the ERP can be questioned through",
      "A bounded investigation loop giving one question up to four tool calls before it must answer",
      "Per module JSON manuals embedded in the binary, so explanations come from documentation rather than invention",
      "Permission gates on every AI lookup that fail closed at each step, written once and shared",
      "A say it simpler button under every answer, which doubles as a ranked log of answers people could not follow",
      "Invoice and purchase order parsing: an IMAP poller, Textract, then a full structured reconstruction of the document",
      "ZIMRA FDMS fiscalisation as a virtual fiscal device, with fiscal days, VAT returns and QR coded receipts",
      "IFRS aligned statements on demand, plus IFRS 9 debt, IFRS 16 leases and IAS 32 equity instruments",
      "Fixed asset register with depreciation runs, revaluations, disposals, verification and capital allowances",
      "Zimbabwean payroll producing the P2, ITF16 and NSSA P4 returns from live run data",
      "Mining, construction, fleet, manufacturing, warehouse, planning and treasury verticals on one ledger",
      "Multi-currency throughout, with one rate store, one reciprocal function and no client side rate maths",
      "An Expo point of sale app with barcode scanning, split payments, offline tolerance and ESC/POS fiscal receipts",
      "Cyclopes, a shared stateless PDF renderer with deterministic S3 keys, parked callbacks and no poison loops",
      "Hermes, a WhatsApp gateway resolving a phone number to a tenant for payslips, statements and balances",
    ],
    techStack: {
      Backend: ["Golang", "Fiber", "GORM"],
      Frontend: ["React", "TypeScript", "Vite", "Next.js", "Tailwind"],
      Mobile: ["React Native", "Expo"],
      Data: ["PostgreSQL", "Redis", "RabbitMQ"],
      AI: ["OpenAI", "MCP", "Textract"],
      Infrastructure: ["Docker Swarm", "Nginx", "AWS", "S3"],
      Documents: ["WeasyPrint", "Python"],
      Compliance: ["ZIMRA FDMS", "IFRS"],
    },
    challenges: [
      "Provisioning a whole isolated stack per tenant without the provisioner ever touching a tenant database",
      "Refusing to reload the nginx ingress until the new tenant's own readyz endpoint answers",
      "Four separate currency lists had grown in one codebase, and a form asking for an inverted rate put a 702 times error into a ledger",
      "Giving an AI read access to production accounting data without it ever answering a question the screen would refuse",
      "One question buying exactly one tool call, so Athena could show the figures or explain them but never both",
      "Parsing an invoice completely enough that a reviewer can check the parse against the original document",
      "A PDF worker that must never requeue to its main queue, so every message acks, parks or dead letters",
      "Keeping one general ledger correct while mining, construction and fleet each insisted their business was different",
    ],
    learnings: [
      "A permission check that differs between two code paths is not duplication, it is the bug where the AI overshares",
      "Deny by default on an AI tool allowlist means tools added later are unreachable until someone decides otherwise",
      "A deterministic S3 key turns retry safety into a naming decision instead of a distributed lock",
      "Storing rates in one direction and inverting them in exactly one server side function removes an entire class of error",
      "Zero values from a document parse must be treated as absent, because a real zero and a missing field are not the same claim",
      "Every time I let a second copy of something exist, it cost a week later",
    ],
    file: "vantagepoint-erp.md",
  },
  "7": {
    intro:
      "The platform the largest forex trading institution in Zimbabwe runs on, serving over five thousand students. A public site, a client portal, a twenty seven section admin console, a learning platform with its own transcoding and transcription pipeline, a bill payments service on top of a bank's biller engine, and an iOS signals app.",
    image: "/img/projects/zfa/site.webp",
    links: [
      {
        label: "WhatsApp the chatbot",
        href: "https://wa.me/263788997601",
        icon: "whatsapp",
      },
    ],
    tags: [
      "NestJS",
      "TypeScript",
      "Next.js",
      "React",
      "React Native",
      "Expo",
      "PostgreSQL",
      "Redis",
      "Socket.IO",
      "OpenAI",
      "MediaConvert",
      "CloudFront",
      "AWS",
      "Sentry",
    ],
    timeline: "Since 2023, still going",
    team: "Solo build for Zhou Forex Academy",
    status: "Live",
    features: [
      "Forty seven backend modules behind a public site, a client portal and a twenty seven section admin console",
      "Learning platform with courses, topics, videos, enrollments, quizzes and per video progress",
      "MediaConvert HLS ladders at 1080p, 720p and 360p, so a phone on a weak signal still plays the lesson",
      "CloudFront signed URLs minted per request, so a paid lesson cannot be passed around as a link",
      "Transcode jobs polled on a schedule, retried three times, with an email to the uploader when one lands",
      "AWS Transcribe in a Lambda that stops one minute short of its own timeout and reports a clean failure",
      "Automatic video summaries triggered by the transcription callback",
      "Quiz generation from transcripts, batched twenty at a time with capped retries and a context ceiling",
      "Ask a question about the video you are watching, with history in Redis for twenty four hours",
      "Payment portal for EcoCash, InnBucks, Mukuru and WorldRemit, with proof of payment review",
      "Deposit requests, withdrawals to mobile wallets, configurable charges and Paynow",
      "Bill payments for DSTV, ZETDC electricity and school fees over ZB Bank's SOAP biller engine",
      "Two school fees flows: registered institutions validated by student number, and a generic biller for primary and secondary",
      "Account validation before payment, so the customer sees the name on the account before committing money",
      "Signals with only pair, direction and status required, because an invented stop loss is worse than none",
      "Append only signal updates, so an instruction someone acted on an hour ago is never rewritten",
      "Two notification lanes, keeping close instructions apart from target hits and notes",
      "A chat room per signal that dies with the call, plus a master trading floor that outlives every one",
      "Paced live prices with per minute and per day credit budgets, each holding a reserve for publishing a signal",
      "KYC, affiliates, memberships, RBAC, audit logs, a WhatsApp chatbot, inbound mail, an ebook library and a shop",
    ],
    techStack: {
      Backend: ["NestJS", "TypeScript", "TypeORM"],
      Frontend: ["Next.js", "React", "Vite", "Tailwind"],
      Mobile: ["React Native", "Expo", "TanStack Query", "Zustand"],
      Data: ["PostgreSQL", "Redis"],
      Media: ["MediaConvert", "CloudFront", "Transcribe", "S3", "Lambda"],
      AI: ["OpenAI"],
      Realtime: ["Socket.IO"],
      Payments: ["Paynow", "Ecocash", "Innbucks", "ZB Bank"],
      Infrastructure: ["AWS", "Elastic Beanstalk", "SES", "SQS", "Sentry"],
    },
    challenges: [
      "Serving paid video without handing students a URL they can forward to everyone they know",
      "A transcription Lambda that must finish, or fail honestly, inside a fifteen minute ceiling",
      "A model asked for eighty quiz questions returns sixty and a truncated object, so generation had to be batched",
      "Zimbabwe does not pay by card, so half the payment methods confirm themselves and half need a human",
      "Learning ZB Bank's biller engine from a folder of PDFs and a SOAP envelope",
      "School fees needing two entirely different flows that had to look like one product",
      "A publisher who sometimes gives an entry price and sometimes says buy gold now, which no strict schema survives",
      "Twelve Data bills per symbol, so twelve instruments every five seconds would have burned the daily allowance in forty five seconds",
      "Resisting the reuse of a support chat module for a trading floor, which would have left both worse",
    ],
    learnings: [
      "Nullable fields are sometimes the correct model, because forcing a value invents one",
      "An append only event log is the only honest way to record instructions people have already acted on",
      "Two notification lanes are worth the effort, since an alert that always interrupts stops being read",
      "Showing how old a price is beats pretending it is live, especially when the vendor bills per symbol",
      "A lifecycle owned by a signal rather than a settings screen removes an entire category of admin work",
      "Leaving a minute of headroom under a timeout turns a killed function into a readable error",
    ],
    file: "zfa-erp.md",
  },
  "8": {
    intro:
      "A savings app for Africa that deliberately holds none of your money. Name a goal, and it breaks the target into a weekly number, coaches you through it in plain language, and lets you join community savings challenges. Ten countries, ten currencies, and an AI that proposes but never writes.",
    image: "/img/projects/melo/site.webp",
    tags: [
      "NestJS",
      "TypeScript",
      "React Native",
      "Expo",
      "Next.js",
      "PostgreSQL",
      "Redis",
      "OpenAI",
      "Paystack",
      "Tamagui",
      "Redux",
      "Docker",
      "Hetzner",
    ],
    timeline: "Ongoing",
    team: "Solo build for Dryback Technology",
    status: "Live on Google Play",
    features: [
      "Savings goals with a target, a deadline and an automatically computed weekly number",
      "Ten goal types covering school fees, rent, groceries, medical, business and emergencies",
      "A vision board you pin goals to, so they are the first thing you see when you open the app",
      "An AI coach that proposes a structured goal from a plain language conversation",
      "Progress logged by conversation too, as a proposal against one goal that you confirm",
      "Every AI action is a proposal and never a write, so a bad parse costs a tap and nothing else",
      "Chat sessions in Redis, goals in Postgres, with prompt credits checked and consumed before the model is called",
      "Admin built savings challenges with weekly tasks and AI written encouragement per week",
      "Coach tone set per challenge: gentle, motivational, celebratory or strict",
      "Ten African countries with their own currencies, and challenges filterable by country",
      "Paystack payments in the customer's local currency rather than converted to dollars",
      "Eight product types from a single extra goal through bundles to a premium subscription",
      "A user balance entity as the single source of truth for quotas, with a weekly prompt reset",
      "Cron driven nudges: Sunday planning, a Wednesday midweek push, Monday challenge progress",
      "Signed one time URLs for verification, password reset and email change, HMAC-SHA256 and timing safe",
      "Four roles including an analytics viewer who can read every dashboard and change nothing",
      "Expo push notifications, a Next.js admin dashboard, and audit logging on admin actions",
    ],
    techStack: {
      Backend: ["NestJS", "TypeScript", "TypeORM"],
      Mobile: ["React Native", "Expo", "Tamagui", "Redux"],
      Web: ["Next.js", "React", "Tailwind", "shadcn"],
      Data: ["PostgreSQL", "Redis"],
      AI: ["OpenAI"],
      Payments: ["Paystack"],
      Security: ["JWT", "HMAC-SHA256", "RBAC"],
      Infrastructure: ["Docker", "Hetzner", "Sentry"],
    },
    challenges: [
      "Choosing to hold no balances at all, which removes a licence problem and a whole class of incident",
      "Letting a model create records without letting a model create records, which the confirmation payload solves",
      "Pricing across ten currencies through one payment provider instead of converting everyone to dollars",
      "Keeping one answer to what a user is entitled to, rather than a quota check per screen",
      "Metering prompt credits before the model call so a runaway conversation cannot outrun the balance",
      "Picking notification times that help rather than annoy, which is a product question wearing a cron expression",
    ],
    learnings: [
      "Deciding what a product will not store is as much a design decision as what it will",
      "An AI that proposes and waits for a confirmation is safe enough to point at a real database",
      "Tone belongs in the data, because some people want a cheerleader and some want to be told off",
      "Local currency pricing is not a nicety in Africa, it is the difference between a sale and an abandoned checkout",
      "One balance entity beats four places that each think they know your quota",
      "A vision board outperformed several features that took ten times as long to build",
    ],
    file: "melo.md",
  },
  "19": {
    intro:
      "The full platform behind a pan-African patient safety summit convened by Medicines for Africa with the African Medicines Agency. A thirteen page public site, a multi step delegate registration flow priced entirely on the server, Stripe checkout with idempotent webhooks, and an admin back office for RSVPs, payments, exports and AI drafted bulk email.",
    image: "/img/projects/mfa/summit-home.webp",
    tags: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind",
      "shadcn",
      "Supabase",
      "PostgreSQL",
      "Stripe",
      "OpenAI",
      "Golang",
      "SES",
      "Vercel",
      "Security",
    ],
    timeline: "2 months",
    team: "Solo build for Medicines for Africa",
    status: "Live",
    features: [
      "Thirteen page public site with the entire programme, themes, speakers and committee driven by typed content modules",
      "Multi step delegate registration with a registrant step, unlimited guests, and a review step before payment",
      "Twelve live prices from three delegate categories across four time windows, resolved in Africa/Kigali",
      "Server authoritative pricing that rebuilds the basket from scratch and never trusts the client",
      "Stripe Checkout with an idempotent webhook keyed on the payment intent, and retry-friendly failures",
      "Expired checkout sessions that release a pending place without ever touching a paid one",
      "Duplicate registration detection, bot honeypot, and a mandatory terms gate before checkout opens",
      "Confirmation, pending reservation and admin notification emails through a self hosted Golang SES service",
      "Full email audit log capturing subject, rendered body, status and error for every send",
      "Admin dashboard with revenue and registration stats, filterable RSVPs and individual RSVP drilldowns",
      "Manual RSVP creation, complimentary places, and offline payment recording for bank transfers",
      "CSV export of RSVPs and payments straight out of streaming API routes",
      "Bulk email with a state driven recipient picker, a send confirmation dialog, and gpt-4o-mini drafting",
      "Superuser and standard admin roles with account activation toggles",
      "Registration kill switch: one environment variable flips the whole site between paid checkout and interest capture",
    ],
    techStack: {
      Frontend: ["Next.js", "React", "TypeScript", "Tailwind", "shadcn"],
      "Data / Auth": ["Supabase", "PostgreSQL", "Row Level Security"],
      Payments: ["Stripe", "Stripe Webhooks"],
      Email: ["Email Lambda (Golang)", "AWS SES"],
      AI: ["OpenAI"],
      Validation: ["Zod", "React Hook Form"],
      Deployment: ["Vercel", "GitHub Actions"],
    },
    challenges: [
      "Keeping pricing authoritative on the server across twelve category and window combinations without a single client side price",
      "Date boundaries that respect the Summit's own timezone instead of whichever region the deployment happens to land in",
      "Stripe idempotency against a partial unique index, which Postgres will not accept as an ON CONFLICT arbiter",
      "Failing loudly in the webhook so Stripe retries, rather than swallowing an error and losing a paid registration",
      "Default deny RLS that serves both a public site and an admin console, without the policies recursing through themselves",
      "Pausing paid registration on a live site with a single environment variable and no code branch",
      "Next 16 moved the goalposts, middleware is proxy.ts now, so the docs in node_modules got read properly instead of guessed at",
    ],
    learnings: [
      "Partial unique indexes and ON CONFLICT do not mix, and the lookup-then-write pattern that replaces them",
      "Next's after() is the cleanest way to fan out email without making a payment provider wait on your SMTP",
      "SECURITY DEFINER helper functions are the trick for RLS policies that need to read the table they protect",
      "An optimistic auth gate plus an authoritative server component check beats trying to do both in one place",
      "Treating conference copy as typed data instead of JSX turns weekly content churn into a one line diff",
      "Feature flagging a whole revenue flow behind one env var is worth the twenty minutes it costs up front",
    ],
    file: "africa-patient-safety-summit.md",
  },
  "20": {
    intro:
      "A readability rating tool for people with low vision. A Chrome extension spots when you are on a site we index, hands you a short survey, and the institution that owns the site watches the scores and the written suggestions land on a dashboard.",
    image: "/img/projects/probable-dribble/survey.webp",
    tags: [
      "React",
      "TypeScript",
      "Redux",
      "Ant Design",
      "Chrome Extension",
      "Django",
      "JWT",
      "Netlify",
      "Heroku",
    ],
    timeline: "June and July 2022",
    team: "Small team, three repos between us",
    status: "Archived, the backend went with Heroku's free tier",
    features: [
      "Manifest V3 extension that reads the active tab URL and asks the backend whether the site is indexed",
      "Popup that offers the survey when there is a match and says so plainly when there is not",
      "Six step survey wizard, ten scored questions plus a free text suggestion",
      "Questions served by the backend, so an institution picks its own rather than taking ours",
      "The site being rated is passed between the two front ends as a single URL query parameter",
      "Institution dashboard for adding a website and reading back its questionnaires",
      "Ten day trend charts for questionnaire volume and per question ratings",
      "Lazy loaded suggestions table, JWT auth held in localStorage",
    ],
    techStack: {
      Dashboard: [
        "React 18",
        "TypeScript",
        "Create React App",
        "Redux Toolkit",
        "PrimeReact",
        "Chakra UI",
        "Chart.js",
        "axios",
      ],
      Survey: ["React 18", "TypeScript", "Ant Design", "Framer Motion"],
      Extension: ["Chrome Extension (Manifest V3)", "JavaScript", "Bootstrap 5"],
      Backend: ["Django", "Django REST Framework", "JWT"],
      Deployment: ["Netlify", "Heroku"],
    },
    challenges: [
      "Three separate front ends that only ever talk to each other through one query parameter",
      "Submitting a questionnaire as ten sequential POSTs with no transaction behind them",
      "A star rating built from five independent booleans, which quietly refuses to let you change your answer",
      "Manifest V3 permissions, where reading the active tab URL is most of what the extension is allowed to do",
      "Telling 'this site is not indexed' apart from 'the request failed', which the extension never bothers to do",
    ],
    learnings: [
      "An accessibility project is the worst place to hang a click handler on a div and leave the real input inert",
      "Guard conditions on five separate useState booleans are a state machine you did not mean to write",
      "A fan out of one request per answer needs a bulk endpoint, or you ship half filled records",
      "Free tier hosting decides how long your project lives, and Heroku decided this one",
      "Pick the component library before you install three of them",
    ],
    file: "probable-dribble.md",
    links: [
      {
        label: "Survey Form Repo",
        href: "https://github.com/IamTyrone/Probable-Dribble-Survey",
      },
      {
        label: "Extension Repo",
        href: "https://github.com/IamTyrone/probable-trible-extension",
      },
    ],
  },
};

export function getProjectDetail(id: string): ProjectDetail | undefined {
  return projectDetails[id];
}
